### ISSUE TITLE
Angular Google Maps module not playing nice..

### ISSUE THREAD

**Issue by RettBehrens** [RettBehrens/brews-cruise#1]
```
node_modules/@agm/core/index.js:2
export * from './directives';
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/everettbehrens/Desktop/wdi-work/brews-cruise/brews-cruise-angular/src/app/app.module.ts:7:1)
```

```
// main modules
export * from './directives';
export * from './services';
// core module
// we explicitly export the module here to prevent this Ionic 2 bug:
// http://stevemichelotti.com/integrate-angular-2-google-maps-into-ionic-2/
export { AgmCoreModule } from './core.module';
//# sourceMappingURL=index.js.map
```

**Comment by RettBehrens** [comment]
not sure what to make of this because it will compile when I start it up with 
ng serve 
but not with 
npm run start
this seems relevant but I've checked my tsconfig file and these changes seem to have already been incorporated in the version I npm installed.
